### ISSUE TITLE
Add title field for dataset

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#329]
Add dataset title field 

- [x] Submit page, see #354
- [ ] Dataset details pages, see #340
- [x] Dataset details page (edit mode) see #355
- [x] Country page, see #307 
- [x] Backend and API #352

Thanks

**Comment by nastasi-oq** [comment]
Fix in #366
